name: Swift Package Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to test"
        required: true
        default: "main"

jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macOS
            command: swift test
          - platform: iOS
            command: xcodebuild test -scheme Simplicity -destination "platform=iOS Simulator,name=iPhone 17,OS=26.1,arch=arm64" -skipPackagePluginValidation
          - platform: tvOS
            command: xcodebuild test -scheme Simplicity -destination "platform=tvOS Simulator,name=Apple TV 4k (3rd generation),OS=26.1,arch=arm64" -skipPackagePluginValidation
          - platform: watchOS
            command: xcodebuild test -scheme Simplicity -destination "platform=watchOS Simulator,name=Apple Watch Ultra 3 (49mm),OS=26.1,arch=arm64" -skipPackagePluginValidation
          - platform: visionOS
            command: xcodebuild test -scheme Simplicity -destination "platform=visionOS Simulator,name=Apple Vision Pro,OS=26.1,arch=arm64" -skipPackagePluginValidation
    name: Test (${{ matrix.platform }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Select latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Display Swift version
        run: swift --version

      - name: Display Xcode version
        run: xcodebuild -version

      - name: Run tests
        run: ${{ matrix.command }}

  test-linux:
    runs-on: ubuntu-latest
    container: swift:6.2
    name: Test (Linux)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Display Swift version
        run: swift --version

      - name: Run tests
        run: swift test
